<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-06-15T15:25:33 IST" name="Suite" finished-at="2024-06-15T15:25:48 IST" duration-ms="15382">
    <groups>
      <group name="ErrorHandling">
        <method signature="ErrorValidation.ErrorValidation()[pri:0, instance:Nirbhay.SeleniumFW.ErrorValidation@517566b]" name="ErrorValidation" class="Nirbhay.SeleniumFW.ErrorValidation"/>
      </group> <!-- ErrorHandling -->
      <group name="PurchaseOrder">
        <method signature="DraftTest.SubmitOrder(java.util.HashMap)[pri:0, instance:Nirbhay.SeleniumFW.DraftTest@6e4566f1]" name="SubmitOrder" class="Nirbhay.SeleniumFW.DraftTest"/>
      </group> <!-- PurchaseOrder -->
    </groups>
    <test started-at="2024-06-15T15:25:33 IST" name="ErrorTest" finished-at="2024-06-15T15:25:48 IST" duration-ms="15382">
      <class name="Nirbhay.SeleniumFW.ErrorValidation">
        <test-method is-config="true" signature="lauchweb()[pri:0, instance:Nirbhay.SeleniumFW.ErrorValidation@517566b]" started-at="2024-06-15T15:25:33 IST" name="lauchweb" finished-at="2024-06-15T15:25:35 IST" duration-ms="2820" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lauchweb -->
        <test-method signature="ErrorValidation()[pri:0, instance:Nirbhay.SeleniumFW.ErrorValidation@517566b]" started-at="2024-06-15T15:25:35 IST" name="ErrorValidation" finished-at="2024-06-15T15:25:36 IST" duration-ms="658" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email password.] but found [Incorrect email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email password.] but found [Incorrect email or password.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at Nirbhay.SeleniumFW.ErrorValidation.ErrorValidation(ErrorValidation.java:41)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ErrorValidation -->
        <test-method is-config="true" signature="closingBrowser()[pri:0, instance:Nirbhay.SeleniumFW.ErrorValidation@517566b]" started-at="2024-06-15T15:25:36 IST" name="closingBrowser" finished-at="2024-06-15T15:25:37 IST" duration-ms="184" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closingBrowser -->
        <test-method is-config="true" signature="lauchweb()[pri:0, instance:Nirbhay.SeleniumFW.ErrorValidation@517566b]" started-at="2024-06-15T15:25:37 IST" name="lauchweb" finished-at="2024-06-15T15:25:40 IST" duration-ms="3174" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lauchweb -->
        <test-method signature="ErrorValidationOnCart()[pri:0, instance:Nirbhay.SeleniumFW.ErrorValidation@517566b]" started-at="2024-06-15T15:25:40 IST" name="ErrorValidationOnCart" finished-at="2024-06-15T15:25:47 IST" duration-ms="7270" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ErrorValidationOnCart -->
        <test-method is-config="true" signature="closingBrowser()[pri:0, instance:Nirbhay.SeleniumFW.ErrorValidation@517566b]" started-at="2024-06-15T15:25:47 IST" name="closingBrowser" finished-at="2024-06-15T15:25:48 IST" duration-ms="954" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closingBrowser -->
      </class> <!-- Nirbhay.SeleniumFW.ErrorValidation -->
    </test> <!-- ErrorTest -->
  </suite> <!-- Suite -->
</testng-results>
